services:
  change-volume-owner:
    image: odoo:14.0
    user: root
    volumes:
      - ./odoo-data:/var/lib/odoo
    command: chown -R odoo:odoo /var/lib/odoo

  web:
    image: odoo:14.0
    ports:
      - "xxxx:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
    depends_on:
      change-volume-owner:
        condition: service_completed_successfully